### ISSUE TITLE
Replace discord.py with a simple API call

### ISSUE THREAD

**Issue by Glukoosi** [Glukoosi/eurojackbot#8]
There is a problem with discord.py async execution in aws lambda. If lambda reuses function instance (runs 'warm'), there will be error `Event loop closed` and execution will fail.

I have not been able to fix this issue and it might be best to just use API calls since there is only one message sent.

**Comment by Visperi** [comment]
Have you tried adding

```py
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
loop.run_until_complete(client.run(discord_key)
```

or similar code to the function `lambda_handler()`? This way a new event loop would be made when the handler is called, and automatically disposed when the script is done.

**Comment by Glukoosi** [comment]
I just tried that and I am still getting `"errorMessage": "Session is closed"` for some reason. I have also tried other various solutions that google offers but I haven't had any luck with those either.

It is rather weird problem since I have not had any problems at my local environment and AWS lambda should be stateless.
